# Overall simulation settings
SIMULATION:
  startTime: "23.10.2025 22:19:30" # "23.10.2025 22:19:30" # "02.01.2026 04:45:41" # UTC time. 'dd.mm.yyyy hh:mm:ss'
  simulationDuration: 0.5 # [hours] 
  deltaT: 0.5 # [sec] Solver max time step 
  integrator: "RKF45" # [RK4(Default), RKF45, RKF78]
  num_satellites: 2
  sat_init_source: "oe" # [oe, vec]

# Satellite parameters
SATELLITES:
  leader:
    m_s: 8.0      # [kg]  Satellite mass
    C_D: 2.2      # [-]   Drag coefficient
    A_D: 0.06     # [m^2] Cross-section area perpendicular to the velocity vector
    C_R: 1.21     # [-]   Radiation pressure coefficient
    A_srp: 0.06   # [m^2] Cross-section area perpendicular to thhe Sun-vector
    I_B: [0.06666667, 0.,         0.,        
          0.,         0.08666667, 0.,
          0.,         0.,         0.03333333] # [kgm^2] Inertia of hub about point Bc in B frame components
    r_BP_B: [0, 0, 1] # TODO Unit vector along principle axis from body (B) to spacecraft face with the largest panel area (P) expressed in B
    r_BA_B: [0, 1, 0] # TODO Unit vector along principle axis from body (B) to spacecraft face with communication antenna (A) expressed in B
    init_OEs:
      a: 6798.        # [km]  Semi-major axis
      e: 0.004161     # [-]   Eccentricity
      i: 97.3166      # [deg] Inclination
      Omega: 6.7052   # [deg] RAAN
      omega: 83.3535  # [deg] Argument of periapsis
      f: 276.82       # [deg] Anomaly
    init_state_vec:
      [6800000, 0, 0, # [m]   [x, y, z    (ECI)
      10000, 0, 0]    # [m/s] vx, vy, vz] (ECI)
    init_att: [[0.3], [0.2], [-0.2]]    # Orientation of Body relative to Inertial expressed using MRP
    init_angvel: [[0.1], [0.15], [0.]] # Angular velocity of Body relative to Inertial expressed in Body
  follower-1:
    m_s: 8.0
    C_D: 2.2
    A_D: 0.06
    C_R: 1.21 
    A_srp: 0.06
    I_B: [0.06666667, 0.,         0.,        
          0.,         0.08666667, 0.,
          0.,         0.,         0.03333333]
    r_BP_B: [0, 0, 1]
    r_BA_B: [0, 1, 0]
    init_OEs:
      a: 6798.
      e: 0.004161
      i: 97.3166 
      Omega: 6.7052
      omega: 83.3535
      f: 286.82
    init_state_vec:
      [6800000, 0, 0,
      10000, 0, 0]
    init_att: [[0.], [0.], [0.]]
    init_angvel: [[0.1], [0.], [0.]] 
  follower-2:
    m_s: 8.0
    C_D: 2.2
    A_D: 0.06
    C_R: 1.21 
    A_srp: 0.06
    I_B: [0.1, 0.,         0.,        
          0.,         0.1, 0.,
          0.,         0.,         0.1]
    r_BP_B: [0, 0, 1]
    r_BA_B: [0, 1, 0]
    init_OEs:
      a: 6798.
      e: 0.004161
      i: 97.3166 
      Omega: 6.7052
      omega: 83.3535
      f: 296.82
    init_state_vec:
      [6800000, 0, 0,
      10000, 0, 0]
    init_att: [[0.], [0.], [0.]]
    init_angvel: [[0.1], [0.], [0.]] 

# TODO
FORMATION_CONTROL:
  form_enabled: true
  form_type: "constant_along_track"  # TODO "constant_along_track" or "circular_projected_orbit"
  leader_mode: "leader_sat" # TODO Might remove to just be decided by 'form_type' "leader_sat" or "common_point"
  form_pos_tolerance: 25.0 # [m] TODO
  form_vel_tolerance: 0.02 # [m/s] TODO
  dwell_time: 300.0 # [s] TODO

  constant_along_track:
    cat_const_separation: 1000.0 # [m] TODO

  circular_projected_orbit:
    cpo_radial_amp: 500.0 # [m] TODO
    cpo_cross_track_amp: 500.0 # [m] TODO
    cpo_phase_deg: 90.0 # [deg] TODO

# Ground station parameters
GROUND_STATIONS:
  gs1:
    gs_tag: gsTrd
    lat: 63.418306  # [deg] Latitude (-90, 90)
    long: 10.399639 # [deg] Longitude (-180, 180)
    alt: 20         # [m] altitude (> 0)
    min_elev: 10    # [deg] Min elevation from horizon where satellite-gs contact is possible (0, 90)
    max_range: -1   # [m] Max distance between satellite-gs where contact is possible (-1 = inf range)
  gs2:
    gs_tag: gsSvbd
    lat: 78.229772
    long: 15.407786
    alt: 20
    min_elev: 5
    max_range: -1

# Electrical Power System parameters (same for all satellites) 
EPS_PARAMETERS:
  bat_storage_capacity: 10.0   # [Wh] Battery max storage capacity
  init_bat_charge: 0.8        # [-] Initial battery charge as fraction of max storage capacity (0, 1)
  RW_base_draw: 1.0           # [W] Idle/baseline power consumption for each RW (> 0)
  OBC_const_draw: 2.0         # [W] Constant OBC power consumption (> 0)
  solar_panels:
    p1:
      nHat_B: [0, 0, 1]     # Panel normal unit vec in body (B)
      panel_area: 0.18      # [m^2] Panel area (> 0)
      panel_efficiency: 0.2 # [W/W] Panel efficiency in converting solar energy to electrical energy (0, 1)
    p2:
      nHat_B: [0, 1, 0]
      panel_area: 0.02
      panel_efficiency: 0.2
    p3:
      nHat_B: [0, 0, -1]
      panel_area: 0.06
      panel_efficiency: 0.2

# Reaction wheel parameters (same for all satellites)
# From RWp100 and RWp015(https://www.bluecanyontech.com/wp-content/uploads/Reaction-Wheels-Full-Product-Line.pdf)
RW_PARAMETERS:
  RW_model: "JitterFullyCoupled"  # [BalancedWheels, JitterSimple, JitterFullyCoupled]
  spinUVecs: [[1., 0., 0.],   # Spin axis unit vector in Body frame [x_B, y_B, z_B]
              [0., 1., 0.],   # (Then number of vectors also define the number of RWs)
              [0., 0., 1.]]
  init_rpm: 0.0               # [RPM] initial wheel speed
  max_rpm: 6000.0             # [RPM] max wheel angular velocity
  maxMomentum: 0.015            # [Nms] Maximum momentum storage capacity
  maxTorque: 0.004            # [Nm] Maximum RW motor torque
  minTorque: 0.00001          # [Nm] Minimum RW motor torque
  # I_RW: 1.                  # [kgm^2] RW inertia about spin axis (calculated from maxMomentum, max_rpm)
  useMinTorque: false
  useFriction: false
  fCoulomb: 0.00005           # [-] Coulomb friction torque model coeff
  fStatic: 1.                 # [-] Static friction torque magnitude
  betaStatic: 1.              # [-] Stribeck friction coefficient, positive turns Stribeck friction on, negative turns this friction off
  cViscous: 1.                # [-] Viscous friction coeff

# Thruster parameters (same for all satellites)
THRUSTER_PARAMETERS:
  thr_pos_B: [1., 0., 0.] # [m] vector with thruster location in B-frame components
  thr_dir_B: [0., 0., 1.] # [-] Unit vector with thruster force direction

  thr_model_override: "None" # ['MOOG_Monarc_1', 'MOOG_Monarc_5', 'MOOG_Monarc_22_6', 'MOOG_Monarc_90HT']
                             # [WARNING] Chosing any of the above values OVERRIDES the thruster params under.
                             # Any other string value will configure a 'Blank_Thruster' model with custom params.

  use_min_pulse_time: false   # [-] Flag if the thruster model should use a minimum impulse time
  min_pulse_time: 0.          # [s] Thruster minimum on time (Requires: use_min_pulse_time == true)
  max_thrust: 5.              # [N] Maximum thruster force
  thrust_blowdown_coeff: [0.] # [-] Vector with polynomial coefficients for fuel mass to thrust blow down model in descending order
  steady_isp: 100.            # [s] Thruster specific impulse/fuel efficiency
  isp_blowdown_coeff: [0.]    # [-] Vector with polynomial coefficients for fuel mass to Isp blow down model in descending order
  area_nozzle: 0.02           # [m^2 ??] Thruster nozzle exhaust cone exit area
  thr_mag_disp: 50.           # [% ??] thruster dispersion percentage


# Magnetorquer parameters (same for all satellites)
MTQ_PARAMETERS:
  temp: false

# Disturbance torques effecting attitude (tbc)
DISTURBANCE_TORQUE:
  temp: false

# Disturbance forces affecting translation
DISTURBANCE_FORCE:
  sphericalHarmonicsDegree:   4 # int >= 2
  useSphericalHarmonics:      true

  useMsisDrag:                true  # First priority
  useExponentialDensityDrag:  false # Second priority

  useSRP:                     true

  useSun3rdBody:              true 
  useMoon3rdBody:             true