# Overall simulation settings
SIMULATION:
  startTime: "23.10.2025 22:19:30" # "23.10.2025 22:19:30" # "02.01.2026 04:45:41" # UTC time. 'dd.mm.yyyy hh:mm:ss'
  simulationDuration: 0.1 # [hours] 
  deltaT: 0.1 # [sec] Solver max time step
  integrator: "RKF45" # [RK4(Default), RKF45, RKF78]
  num_satellites: 2
  sat_init_source: "oe" # [oe, vec, (tle)]

# Satellite parameters
SATELLITES:
  leader:
    m_s: 8.0      # [kg]  Satellite mass
    C_D: 2.2      # [-]   Drag coefficient
    A_D: 0.06     # [m^2] Cross-section area perpendicular to the velocity vector
    C_R: 1.21     # [-]   Radiation pressure coefficient
    A_srp: 0.06   # [m^2] Cross-section area perpendicular to thhe Sun-vector
    I_B: [0.06666667, 0.,         0.,        
          0.,         0.08666667, 0.,
          0.,         0.,         0.03333333] # [kgm^2] Inertia of hub about point Bc in B frame components
    init_OEs:
      a: 6798.        # [km]  Semi-major axis
      e: 0.004161     # [-]   Eccentricity
      i: 97.3166      # [deg] Inclination
      Omega: 6.7052   # [deg] RAAN
      omega: 83.3535  # [deg] Argument of periapsis
      f: 276.82       # [deg] Anomaly
    init_state_vec:
      [6800000, 0, 0, # [m]   [x, y, z    (ECI)
      10000, 0, 0]    # [m/s] vx, vy, vz] (ECI)
    init_att: [[0.3], [0.2], [-0.2]]    # Orientation of Body relative to Inertial expressed using MRP
    init_angvel: [[0.1], [0.15], [0.]] # Angular velocity of Body relative to Inertial expressed in Body
  follower-1:
    m_s: 8.0
    C_D: 2.2
    A_D: 0.06
    C_R: 1.21 
    A_srp: 0.06
    I_B: [0.06666667, 0.,         0.,        
          0.,         0.08666667, 0.,
          0.,         0.,         0.03333333]
    init_OEs:
      a: 6798.
      e: 0.004161
      i: 97.3166 
      Omega: 6.7052
      omega: 83.3535
      f: 286.82
    init_state_vec:
      [6800000, 0, 0,
      10000, 0, 0]
    init_att: [[0.], [0.], [0.]]
    init_angvel: [[0.1], [0.], [0.]] 
  follower-2:
    m_s: 8.0
    C_D: 2.2
    A_D: 0.06
    C_R: 1.21 
    A_srp: 0.06
    I_B: [0.06666667, 0.,         0.,        
          0.,         0.08666667, 0.,
          0.,         0.,         0.03333333]
    init_OEs:
      a: 6798.
      e: 0.004161
      i: 97.3166 
      Omega: 6.7052
      omega: 83.3535
      f: 296.82
    init_state_vec:
      [6800000, 0, 0,
      10000, 0, 0]
    init_att: [[0.], [0.], [0.]]
    init_angvel: [[0.1], [0.], [0.]] 

# Reaction wheel parameters (same for all satellites)
# From RWp100 and RWp015(https://www.bluecanyontech.com/wp-content/uploads/Reaction-Wheels-Full-Product-Line.pdf)
RW_PARAMETERS:
  RW_model: "BalancedWheels"  # [BalancedWheels, JitterSimple, JitterFullyCoupled]
  spinUVecs: [[1., 0., 0.],   # Spin axis unit vector in Body frame [x_B, y_B, z_B]
              [0., 1., 0.],     # (Then number of vectors also define the number of RWs)
              [0., 0., 1.]]
  init_rpm: 0.0               # [RPM] initial wheel speed
  max_rpm: 6000.0             # [RPM] max wheel angular velocity
  maxMomentum: 0.015            # [Nms] Maximum momentum storage capacity
  maxTorque: 0.004            # [Nm] Maximum RW motor torque
  minTorque: 0.00001          # [Nm] Minimum RW motor torque
  # I_RW: 1.                  # [kgm^2] RW inertia about spin axis (calculated from maxMomentum, max_rpm)
  useMinTorque: false
  useFriction: false
  fCoulomb: 0.00005           # [-] Coulomb friction torque model coeff
  fStatic: 1.                 # [-] Static friction torque magnitude
  betaStatic: 1.              # [-] Stribeck friction coefficient, positive turns Stribeck friction on, negative turns this friction off
  cViscous: 1.                # [-] Viscous friction coeff

# Thruster parameters (same for all satellites)
THRUSTER_PARAMETERS:
  temp: false

# Magnetorquer parameters (same for all satellites)
MTQ_PARAMETERS:
  temp: false

# Disturbance torques effecting attitude (tbc)
DISTURBANCE_TORQUE:
  temp: false

# Disturbance forces affecting translation
DISTURBANCE_FORCE:
  sphericalHarmonicsDegree:   4 # int >= 2
  useSphericalHarmonics:      true

  useMsisDrag:                true # First priority
  useExponentialDensityDrag:  false # Second priority

  useSRP:                     true

  useSun3rdBody:              true 
  useMoon3rdBody:             true